config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/filter", to: "flats#filter", as: :filter
  resources :flats do
    collection do
      get :filter
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  def filter
    if params[:term] == ""
      redirect_to flats_path
    else
      @flats = Flat.where("name LIKE '%#{params[:term]}%'")
      
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <%= simple_form_for (@flat) do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :address %>
            <%= f.input :number_of_guests %>
            <%= f.input :price_per_night %>
            <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/flats/filter.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>All flats</h1>
      <div class="content">
        <div class="cards">
        <% @flats.each do |flat|%>
            <div class="flat-card">
            <div class="flat-card-top">
                <h2> <%= flat.name %> </h2>
                <p> <%= flat.address %></p>
                <ul>
                    <li>
                      <i class="fas fa-user-friends"></i> <%= flat.number_of_guests%>
                    </li>
                    <li>
                      <i class="fas fa-euro-sign"></i> <%= flat.price_per_night%>
                    </li>
                </ul>
            </div>
            <div class="flat-card-bottom">
                <%= link_to "More info", flat_path(flat), class: "btn btn-primary"%>
                <%= link_to "Edit flat", edit_flat_path(flat), class: "btn btn-info"%>
                <%= link_to "Delete flat", flat_path(flat), method: "delete" , data: { confirm: "Are you sure?" }, class: "btn btn-danger"%>
            </div>
            </div>
        <% end %>
        </div>
      </div>
      
      
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>All flats</h1>
      <div class="content">
        <div class="cards">
        <% @flats.each do |flat|%>
            <div class="flat-card">
            <div class="flat-card-top">
                <h2> <%= flat.name %> </h2>
                <p> <%= flat.address %></p>
                <ul>
                    <li>
                      <i class="fas fa-user-friends"></i> <%= flat.number_of_guests%>
                    </li>
                    <li>
                      <i class="fas fa-euro-sign"></i> <%= flat.price_per_night%>
                    </li>
                </ul>
            </div>
            <div class="flat-card-bottom">
                <%= link_to "More info", flat_path(flat), class: "btn btn-primary"%>
                <%= link_to "Edit flat", edit_flat_path(flat), class: "btn btn-info"%>
                <%= link_to "Delete flat", flat_path(flat), method: "delete" , data: { confirm: "Are you sure?" }, class: "btn btn-danger"%>
            </div>
            </div>
        <% end %>
        </div>
      </div>
      
      
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <%= simple_form_for (@flat) do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :address %>
            <%= f.input :number_of_guests %>
            <%= f.input :price_per_night %>
            <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="thumbnail"></div>

<div class="info">
    <div class="container">
    <div class="row">
        <div class="col">
            <div class="internal-container">
              <div class="details">
                <div class="details-card">
                  <h2> <%= @flat.name %> </h2>
                  <p> <%= @flat.address %> </p>
                </div>
                <div class="details-card">
                  <h3>A bit more about this flat...</h3>
                  <p> <%= @flat.description %> </p>
                </div>
              </div>
              <div class="booking">
                <div class="details-card book">
                  <a class="btn btn-success" href="">Book now!</a>
                </div>
                <div class="details-card">
                  <h2> Details </h2>
                  <ul>
                    <li>
                      <i class="fas fa-user-friends"></i> <%= @flat.number_of_guests%>
                    </li>
                    <li>
                      <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night%>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <%= link_to "Simple AirBnb", flats_path, class: "logo"%>
      <%= link_to "Add a flat", new_flat_path, class: "btn btn-primary"%>
      <form action= <%= filter_flats_path %>>
        <input type="text" name="term" value="<%= params[:term] %>">
        <input type="submit">
      </form>
      
    </div>
    <%= yield %>
  </body>
</html>